# Generated by Django 6.0.5 on 2026-05-27 15:26

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_aboutpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, default=''),
        ),
    ]
